Review doc 05
dojot/flowbroker pull request #291
Opened 2020-09-29 18:30 UTC by mprevide

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

* **Other information**:

2020-10-01 18:10 UTC, eduardogmisiuk requested changes

2020-10-01 18:10 UTC, eduardogmisiuk commented on lib/README.md
> +**ATTENTION**: The `id` to add the node via API (when request `/flows/v1/node`) must be the same as `name` and `id` defined in `getMetadata` in the class that extends `dojot.DataHandlerBase`. And wit
This paragraph is kind of confusing. My suggestion is to create a list of places where the user should make sure that the id/name matches.

2020-10-01 18:10 UTC, eduardogmisiuk commented on lib/samples/kelvin/README.md
>  This is a Dojot's flowbroker node that converts a Celcius temperature
Celsius

2020-10-01 18:10 UTC, eduardogmisiuk commented on lib/samples/kelvin/README.md
> +Note: the previous command requires the `jq`and `curl` command, you can install it on on Debian-based Linux distributions with the following command:
\`jq\` and

2020-10-01 18:10 UTC, eduardogmisiuk commented on lib/samples/kelvin/README.md
> +sudo apt-get install curl
Merge in one command.

2020-10-01 18:10 UTC, eduardogmisiuk commented on lib/samples/kelvin/package.json
>    "description": "This is a sample of node that transforms a given temperature from celcius to kenvin",
from Celsius to Kelvin

2020-10-01 19:16 UTC, mprevide commented on lib/README.md
>  Any HTML element provided in the node template can specify a data-i18n attribute to provide the message identify to use. For example:
It must be 'identity'. I'll try to remake that phrase.

2020-10-01 22:43 UTC, thiagodpf approved these changes
it looks great to me!

2020-10-02 12:32 UTC, eduardogmisiuk commented on lib/README.md
> +**Note:** If you need to change the source code of the node and seeing them reflected, you need to: **rebuild the container**; **push it to the registry again with a new tag**; **remove the node from
and see them reflected

2020-10-02 12:32 UTC, eduardogmisiuk commented on lib/README.md
> +To facilitate adding the node to the flowbroker, try to follow these intrusions:
Suggestion:

To facilitate the addition of a node to the Flowbroker, follow these instructions:

2020-10-02 12:32 UTC, eduardogmisiuk commented on lib/README.md
> +The `id` when request `/flows/v1/node` must be the same as `name` and `id` defined in `getMetadata` in the class that extends `dojot.DataHandlerBase`.
Suggestion:

The \`id\` sent in a request to the \`/flows/v1/node\` endpoint must be the same as the  \`name\` and the \`id\` defined in the \`getMetadata\` function inside the class that extends \`dojot.DataHandlerBase\`.

2020-10-02 12:32 UTC, eduardogmisiuk commented on lib/README.md
> +When creating the html called in the `getNodeRepresentationPath` method also in the class that extends `dojot.DataHandlerBase` , the references within this html listed below must have the same `id`/`
html -> HTML
method also -> method and also

2020-10-02 12:32 UTC, eduardogmisiuk commented on lib/README.md
> +##### **When creating the node front end - html**
HTML

2020-10-02 12:34 UTC, eduardogmisiuk commented on README.md
> +AMQP_URL               | RabbitMQ host address    | amqp://rabbitmq  | url
These AMQP parameters are not alphabetically ordered.

2020-10-02 12:57 UTC, eduardogmisiuk approved these changes
Nice!

2020-10-03 01:32 UTC, thiagodpf approved these changes
:1st_place_medal:

2020-10-05 11:43 UTC, merged