[Flowbroker] Remove travis and make changes to use github actions
dojot/flowbroker pull request #340
Opened 2021-03-15 17:21 UTC by marianoleonardo

dojot/dojot#1913

2021-03-15 21:46 UTC, thiagodpf submitted a review, later dismissed

2021-03-16 12:36 UTC, mprevide commented
Did you test when the dread (docker-compose) has some error?  
Because I think It's important to see if some error happen in the dread the github actions return a status fail.

2021-03-16 18:08 UTC, mprevide commented
> Did you test when the dread (docker-compose) has some error?
> Because I think It's important to see if some error happen in the dread the github actions return a status fail.

you might be able to change something in the code to return something different, such as a name in a key in response to a request in the API

2021-03-18 12:12 UTC, mprevide commented
> > Did you test when the dread (docker-compose) has some error?
> > Because I think It's important to see if some error happen in the dread the github actions return a status fail.
> 
> you might be able to change something in the code to return something different/error, such as a name in a key in response to a request in the API

Did you test?

2021-03-19 19:13 UTC, mprevide commented on .github/workflows/main.yml
> +        name: ${{ steps.get_owner.outputs.owner }}/flowbroker
It's necessary to build the image `dojot/flowbroker-context-manager` too
Always look at /travis/publish.sh to see what it did.

2021-03-19 19:14 UTC, mprevide requested changes
I left some comments

2021-03-30 13:36 UTC, mprevide commented on .github/workflows/main.yml
> +  docker-compose:
Integration tests?

2021-03-31 11:42 UTC, mprevide approved these changes

2021-03-31 14:38 UTC, mprevide commented on .github/workflows/main.yml
> +        npm run build --if-present
There're 3 packages
 - inside lib
 - inside orchestrator
 - inside contextManager

2021-03-31 14:38 UTC, mprevide requested changes
I left one comment

2021-04-05 14:09 UTC, mprevide approved these changes

2021-04-06 22:09 UTC, thiagodpf approved these changes

2021-04-07 12:47 UTC, merged